# Generated by Django 4.2.7 on 2025-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_position_alter_user_position'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='position',
        ),
        migrations.AddField(
            model_name='test',
            name='positions',
            field=models.ManyToManyField(blank=True, help_text="Test qaysi positionlar uchun mo'ljallangan", related_name='tests', to='users.position', verbose_name='Positions'),
        ),
    ]
