# Generated by Django 4.2.7 on 2025-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_position_test_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='random_questions_count',
            field=models.IntegerField(default=0, help_text='0 = barcha savollar, >0 = shuncha ta random savol tanlanadi', verbose_name='Random Questions Count'),
        ),
        migrations.AddField(
            model_name='test',
            name='show_answers_immediately',
            field=models.BooleanField(default=True, help_text="Har bir savoldan keyin javob ko'rsatilsinmi", verbose_name='Show Answers Immediately'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_mode',
            field=models.CharField(choices=[('webapp', 'WebApp'), ('telegram', 'Telegram'), ('both', 'Both (WebApp and Telegram)')], default='both', help_text='Test qayerda yechiladi', max_length=10, verbose_name='Test Mode'),
        ),
    ]
