# Generated by Django 4.2.7 on 2025-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_random_questions_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='trial_questions_count',
            field=models.IntegerField(default=10, help_text='Trial test uchun nechta savol berilsin', verbose_name='Trial Questions Count'),
        ),
    ]
