# Generated by Django 4.2.7 on 2025-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_trial_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=2, help_text='Foydalanuvchi necha marta urinish berishi mumkin', verbose_name='Max Attempts'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Qaysi urinish', verbose_name='Attempt Number'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Test yakunlanganmi', verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed at'),
        ),
    ]
