# Generated by Django 4.2.7 on 2025-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_max_attempts_testresult_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Trial testmi yoki haqiqiy testmi', verbose_name='Is Trial'),
        ),
    ]
