# Generated by Django 4.2.7 on 2025-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_testresult_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_trial_attempts',
            field=models.IntegerField(default=1, help_text='Foydalanuvchi necha marta trial test ishlashi mumkin', verbose_name='Max Trial Attempts'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=2, help_text='Foydalanuvchi necha marta urinish berishi mumkin (real testlar uchun)', verbose_name='Max Attempts'),
        ),
    ]
