# Generated by Django 4.2.7 on 2025-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_position_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Blocked At'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Block qilinish sababi', null=True, verbose_name='Block Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='User block qilinganmi (cheating yoki boshqa sabablar)', verbose_name='Is Blocked'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_tests_taken',
            field=models.JSONField(blank=True, default=list, help_text='Qaysi testlardan trial test olgan', verbose_name='Trial Tests Taken'),
        ),
    ]
