# Generated by Django 4.2.7 on 2025-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_blocked_at_user_blocked_reason_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='Telegram orqali bildirishnomalar yoqilganmi', verbose_name='Notification Enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_is_premium',
            field=models.BooleanField(default=False, verbose_name='Telegram Premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_language_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telegram Language Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username'),
        ),
    ]
