# Generated by Django 4.2.7 on 2025-11-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_notification_enabled_user_telegram_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_language_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text="Telegram ID - TelegramProfile bilan bog'lanish uchun", null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram First Name')),
                ('telegram_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Last Name')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('telegram_language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telegram Language Code')),
                ('telegram_is_premium', models.BooleanField(default=False, verbose_name='Telegram Premium')),
                ('telegram_is_bot', models.BooleanField(default=False, verbose_name='Is Bot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Telegram Profile',
                'verbose_name_plural': 'Telegram Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
