# Generated by Django 4.2.7 on 2025-11-14 18:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_telegram_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Xabar sarlavhasi', max_length=255, verbose_name='Title')),
                ('message', ckeditor.fields.RichTextField(help_text='Xabar matni (HTML formatida)', verbose_name='Message')),
                ('send_to_all', models.BooleanField(default=False, help_text="Barcha bot a'zolariga yuborish", verbose_name='Send to All')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Xabar yuborilgan vaqt', null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('total_recipients', models.IntegerField(default=0, help_text='Jami yuborilgan foydalanuvchilar soni', verbose_name='Total Recipients')),
                ('successful_sends', models.IntegerField(default=0, help_text='Muvaffaqiyatli yuborilgan', verbose_name='Successful Sends')),
                ('failed_sends', models.IntegerField(default=0, help_text='Xatolik bilan yuborilgan', verbose_name='Failed Sends')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recipients', models.ManyToManyField(blank=True, help_text='Xabarni oladigan foydalanuvchilar', to=settings.AUTH_USER_MODEL, verbose_name='Recipients')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
