# Generated by Django 4.2.7 on 2025-11-14 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Foydalanuvchi Telegram ID', verbose_name='Telegram ID')),
                ('error_message', models.TextField(help_text='Xatolik xabari', verbose_name='Error Message')),
                ('error_type', models.CharField(blank=True, help_text='Xatolik turi', max_length=100, null=True, verbose_name='Error Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='users.notification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_errors', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Error',
                'verbose_name_plural': 'Notification Errors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification', 'created_at'], name='users_notif_notific_d3a8e4_idx'), models.Index(fields=['user', 'created_at'], name='users_notif_user_id_180313_idx')],
            },
        ),
    ]
